DROP TABLE IF EXISTS news;

CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  pic TEXT,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)